### ISSUE TITLE
wrong answer(e.g. 1+23=4)

### ISSUE THREAD

**Issue by li-yiqing** [theSmitChawda/calculator-android-application#2]
nice layout but the logic is wrong. you directly set the last input char as the right operand, which caused the problem above. you should do the same as you did on the left operand, use Double.parseDouble!

**Comment by sayoriaaa** [comment]
here is one solution: replace `rightOperand=xx;` in each btnxx by `isOperatorPresent = false;` then add `rightOperand = Double.parseDouble(results.getText().toString());` in `btnEquals` above the sentence `calculateResults();`

**Comment by li-yiqing** [comment]
delete the assign of right operand in each btn function, replace the `rightOperand= x` by `isOperatorPresent = false;` add `rightOperand = Double.parseDouble(results.getText().toString());` above the sentence `calculateResults();` in function `btnEquals.setOnClickListener` that will work ~~~

**Comment by theSmitChawda** [comment]
The ExpressionSolver class has been added to handle all types of BODMAS (or PEMDAS) operations.
